nosana:
  description: Nosana docker in docker

global:
  image: nosana/podman:latest

jobs:
  - name: build
    environment:
      CONTAINER_HOST: tcp://localhost:8080
    commands:
      - docker build . -t my-apline-container
